---
title: "Biplot packages in R"
author: "Michael Friendly"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Why talk?

There are quite a few implementations of biplots in R, but IMHO, **none** are sufficiently general to:

* become a current standard, 
* with wide applicability, and 
* easily used within modern R, 
* encompassing the latest developments in the `tidyverse` and the `ggplot2` framework. 

Does anyone want to join me in making biplots more accessible and easy to use in modern R?

### My problem

My problem, as a **user** and **explainer** is that with none of these can I 

* easily create and describe simple examples of biplot methods 
* with all the graphical attributes I want to control for a given example.

### What I'd like

* Provide a **common interface** for PCA / LDA and **all** related methods: E.g., 

> {`prcomp() / princomp() / MASS::lda(), ...} -> a common "biplot" class object.

* Easily allow the different **scalings**, to show row/column variables in principal or
  standard coordinates.
* When there are groups, provide nice data ellipses or other bivariate summaries (convex hulls, ...)
  for each group, with fine control over graphical attributes (color, fill, ...), 
  possibly direct labels for groups rather than a legend, etc.
* show row/observation points as points or observation labels. 
* Be able to control the point/character size easily. Be able to filter out some point labels to highlight some more interesting ones.
* For variable vectors, control all graphical attributes: color, linewidth, font/sizes for variable names, etc.


## Current state: What packages exist?

* **base R**: `prcomp()`, `princomp()` --> `biplot()`

* **FactoMineR, factoextra**: `PCA()` --> `fviz_pca()`, `fviz_pca_ind()`, `fviz_pca_var()`

* **adegraphics** Lattice-based. Development of `ade4`, "dudi" framework -> `biplot()`

* **biplotEZ** based on _Understanding Biplots_, `UBbipl` package

* **ggbiplot**: Original by Vincent Yu, devel now at https://github.com/friendly/ggbiplot 

